name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Basic CI - Test and Build
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint frontend
      run: |
        cd frontend
        npm run lint

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Test Docker build
      run: |
        cp .env.example .env
        docker compose build
        echo "✅ Docker build successful"

    - name: Security audit
      run: |
        cd backend && npm audit --audit-level high || true
        cd ../frontend && npm audit --audit-level high || true

  # Docker Hub push (optional)
  docker-push:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: secrets.DOCKER_USERNAME != ''

    - name: Build and push to Docker Hub
      run: |
        cp .env.example .env
        docker compose build
        docker tag teamtask-nginx ${{ secrets.DOCKER_USERNAME }}/teamtask:latest || echo "Docker push skipped - no credentials"
        docker push ${{ secrets.DOCKER_USERNAME }}/teamtask:latest || echo "Docker push skipped - no credentials"
      if: secrets.DOCKER_USERNAME != ''
