name: Dependencies Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Update backend dependencies
      run: |
        cd backend
        npm update
        npm audit fix || true

    - name: Update frontend dependencies
      run: |
        cd frontend
        npm update
        npm audit fix || true

    - name: Test build after updates
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci && npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates:
          - Backend package updates
          - Frontend package updates
          - Security fixes applied
          
          Please review the changes and test thoroughly before merging.
        branch: dependency-updates
        delete-branch: true
